# The Walls B&W concept layout

# Text classes
alltext:
  align: center
  font: Calibri

title:
  extends: alltext
  x: 90
  y: 120
  width: 635
  height: 50
  font: Calibri bold 42

type:
  extends: alltext
  x: 90
  y: 180
  width: 625
  font_size: 28

effect:
  extends: alltext
  x: 90
  y: 240
  width: 625
  font: Calibri italic
  font_size: 22

description:
  extends: alltext
  x: 100
  y: 680
  width: 625
  height: 100
  font: Calibri bold italic
  font_size: 22
desc: # alias
  extends: description

details:
  extends: description
  y: += 80
  height: 250
  font: Calibri italic

lower_right:
  x: 675
  y: 975
  width: 75
  height: 75
  font_size: 18
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 75
  y: 975
  width: 75
  height: 75
  font_size: 18
  valign: bottom
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 120
  y: 1025
  width: 675
  height: 25
  font_size: 10
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright

# Artwork
art:
  x: 262.5
  y: 310
  width: 300
  height: 300

# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050
  fill_color: '#000000'

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 48
  fill_color: '#ffffff' # Overwrite above black square with white.
